export const SAVE_SHIPPING_REQUEST = 'SAVE_SHIPPING_REQUEST';
export const SAVE_SHIPPING_SUCCESS = 'SAVE_SHIPPING_SUCCESS';
export const SAVE_SHIPPING_FAILURE = 'SAVE_SHIPPING_FAILURE';

export const GET_SHIPPING_REQUEST = 'GET_SHIPPING_REQUEST';
export const GET_SHIPPING_SUCCESS = 'GET_SHIPPING_SUCCESS';
export const GET_SHIPPING_FAILURE = 'GET_SHIPPING_FAILURE';
