export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAILURE = 'USER_REGISTER_FAILURE';

export const USER_Login_REQUEST = 'USER_Login_REQUEST';
export const USER_Login_SUCCESS = 'USER_Login_SUCCESS';
export const USER_Login_FAILURE = 'USER_Login_FAILURE';

export const USER_LOGOUT = 'USER_LOGOUT';

export const ALL_USERS_DATA_REQUEST = 'ALL_USERS_DATA_REQUEST';
export const ALL_USERS_DATA_SUCCESS = 'ALL_USERS_DATA_SUCCESS';
export const ALL_USERS_DATA_FAILURE = 'ALL_USERS_DATA_FAILURE';
